// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

// / Default [FirebaseOptions] for use with your Firebase apps.
// /
// / Example:
// / ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
// / ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwv-aQYgvWDgR_0UloDcbLMFqHFLytoOM',
    appId: '1:90174131186:web:6d28859a0be4c2be6b796b',
    messagingSenderId: '90174131186',
    projectId: 'restaurant-marketplace-60929',
    authDomain: 'restaurant-marketplace-60929.firebaseapp.com',
    storageBucket: 'restaurant-marketplace-60929.appspot.com',
    measurementId: 'G-B9CRTJVF00',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJrQ8ENJGjSP2LWqldFNOXN0Zo3Y54Tj0',
    appId: '1:90174131186:android:7cb32662610e9d4e6b796b',
    messagingSenderId: '90174131186',
    projectId: 'restaurant-marketplace-60929',
    storageBucket: 'restaurant-marketplace-60929.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBN9NJfT_qPwuX_hYwG58-oHdu0l-PnPpQ',
    appId: '1:90174131186:ios:b482093dcb02e97f6b796b',
    messagingSenderId: '90174131186',
    projectId: 'restaurant-marketplace-60929',
    storageBucket: 'restaurant-marketplace-60929.appspot.com',
    iosClientId: '90174131186-etd7peksvqeltkhqkidm86jiqb5f8jn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantMarketplaceh',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBN9NJfT_qPwuX_hYwG58-oHdu0l-PnPpQ',
    appId: '1:90174131186:ios:b482093dcb02e97f6b796b',
    messagingSenderId: '90174131186',
    projectId: 'restaurant-marketplace-60929',
    storageBucket: 'restaurant-marketplace-60929.appspot.com',
    iosClientId: '90174131186-etd7peksvqeltkhqkidm86jiqb5f8jn0.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantMarketplaceh',
  );
}
